name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y asciidoctor

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build & Test
        run: cargo test

      - name: Install cargo-deb
        if: startsWith(github.ref, 'refs/tags/')
        run: cargo install cargo-deb

      - name: Build Linux release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          scripts/lin/mk-man.sh
          cargo build --release
          scripts/lin/mk-tarball.sh
          cargo deb

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/dist/termcalc-*.tar.gz 
            target/debian/termcalc_*.deb
